;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        aj/duplicate-current-line-or-region
        aj/smart-beginning-of-line
        aj/yank-or-pop
        aj/yank-pop-forwards
        backward-sexp
        comment-indent-new-line
        comment-or-uncomment-current-line-or-region
        cycle-spacing
        delete-pair
        drag-stuff-down
        fill-paragraph
        forward-sexp
        helm-M-x
        kill-region
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-open-at-point
        org-self-insert-command
        org-table-copy-down
        org-todo
        replace-string
        split-line
        upcase-region
        wdired--self-insert
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        markdown-outdent-or-delete
        ))
