;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        aj/duplicate-current-line-or-region
        aj/smart-beginning-of-line
        aj/yank-or-pop
        backward-sexp
        comment-indent-new-line
        comment-or-uncomment-current-line-or-region
        dabbrev-expand
        delete-pair
        downcase-region
        drag-stuff-down
        end-of-buffer
        forward-sexp
        helm-M-x
        kill-region
        markdown-outdent-or-delete
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-fill-paragraph
        org-force-self-insert
        org-kill-line
        org-open-at-point
        org-self-insert-command
        org-table-copy-down
        org-transpose-words
        python-nav-backward-up-list
        split-line
        wdired--self-insert
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        dired-flag-file-deletion
        replace-string
        scroll-other-window
        ))
