(add-to-list 'load-path "~/.emacs.d/plugins/magit")
(add-to-list 'load-path "~/.emacs.d/plugins/timeclock-x")
(add-to-list 'load-path "~/.emacs.d/plugins/emacs-soap-client")
(add-to-list 'load-path "~/.emacs.d/plugins/auto-complete")
(add-to-list 'load-path "~/.emacs.d/plugins/auto-complete-etags")
(add-to-list 'load-path "~/.emacs.d/plugins/zencoding-mode")
(add-to-list 'load-path "~/.emacs.d/plugins/hs-lint")
(add-to-list 'load-path "~/.emacs.d/plugins/yasnippet")
(add-to-list 'load-path "~/.emacs.d/plugins/mk-project")
(add-to-list 'load-path "~/.emacs.d/plugins/remember-el")
(add-to-list 'load-path "~/.emacs.d/plugins/org-mode")
(add-to-list 'load-path "~/.emacs.d/plugins/color-theme")
(add-to-list 'load-path "~/.emacs.d/plugins/color-theme/themes")
(add-to-list 'load-path "~/.emacs.d/plugins/color-theme-tango-2")
(add-to-list 'load-path "~/.emacs.d/plugins/php-mode")

(provide 'arvid-loadpaths)