(let* ((passwords '(("Diverse / arvid" "e%7;hTYC#8?z")
					("root bahnhof / root" "BnH83gL!L12#")
					("SSH Server / www-data" "3[%5vVgbzsFm")
					("Typo3 Database / typo3" "4X8U]-PFqf.5")
					("database / typo3_admin" "@R_CeP&c9spe")
					("Loopia / gluteus.se" "mlm7wqab")
					("Databas root / root" "0aur0ra0")))
	   (label (mapcar 'car passwords))
	   (choice (ido-completing-read "Account: " label nil t)))
  (kill-new (car (assoc-default choice passwords 'string=))))

